name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: Build Android App
      run: |
          cd android-app
          ./gradlew build --stacktrace

    - name: Build with Gradle
      run: |
          cd android-app
          ./gradlew build

  run-instrumented-tests:
    runs-on: macos-latest
    steps:
    - name: make gradlew available
      run: |
          cd android-app
          chmod +x gradlew
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Run instrumented tests for TankBattle
      uses: reactivecircus/android-emulator-runner@v2
      with:
        profile: Nexus 6
        api-level: 29
        arch: x86_64
        working-directory: ./android-app
        script: ./gradlew connectedCheck